### ISSUE TITLE
Error in WP

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wpsparql#17]
@acorbi -- not sure if this error has anything to do with not being able to upload a new slider but when I googled it sent me here: 

![image](https://user-images.githubusercontent.com/14996905/35480965-8a1cebfa-0448-11e8-884b-484560396ed7.png)

**Comment by acorbi** [comment]
Tackling this issue on https://github.com/OpenDevelopmentMekong/wpsparql/issues/16
